name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install sdkmanager
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y android-sdk
          sudo apt-get install build-essential -y
          sudo apt-get install libstdc++6 -y
          sudo apt-get install aidl -y

      - name: Add sdkmanager to PATH
        run: |
          echo "y" | sdkmanager --install "build-tools;29.0.2"

      - name: Install Android Build Tools
        run: |
          echo y | sdkmanager "build-tools;29.0.2"

      - name: Add Build Tools to PATH
        run: |
          export PATH=$PATH:$ANDROID_SDK_ROOT/build-tools/29.0.2

      - uses: actions/checkout@v2

      - name: Cache Buildozer global directory
        uses: actions/cache@v2
        with:
          path: .buildozer_global
          key: buildozer-global-${{ hashFiles('buildozer.spec') }}

      - uses: actions/cache@v2
        with:
          path: .buildozer
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: master
